### ISSUE TITLE
We need better documentation for running locally

### ISSUE THREAD

**Issue by axtimwalde** [JaneliaSciComp/SAM_service#2]
I have tried this now for about an hour, and I get the SAM service to run, and also nginx, but it wasn't straight forward and nginx only shows the frontend and then fails to forward the requests.  We should include an nginx.conf file that works on localhost, serves only localhost, and instructions to run nginx as a simple user process and not as a system service (i.e.
```
nginx -p `pwd` -c nginx.local.conf
```
).  This is my current state, I assume I am missing something, probably the uvicorn stuff?  All this is very cryptic:
```
http {
  upstream uvicorn {
    server unix:/tmp/uvicorn.sock;
  }

  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }

  server {
    listen 8080 default_server;
    server_name 127.0.0.1 localhost;
    client_max_body_size 20M;
    access_log nginx_access.log combined;
    error_log nginx_error.log;


    location / {
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_redirect off;
      proxy_buffering off;
      proxy_pass http://uvicorn;
    }
  }
}

# events context
events {
  worker_connections 1024;
}

pid nginx.pid;
error_log nginx_error.log;
```

**Comment by neomorphic** [comment]
Agreed, I will walk through the steps on a windows laptop with WSL2 installed and document the process.

**Comment by neomorphic** [comment]
Added additional documentation for running the service based on a fresh install of the whole stack on a windows laptop.
See 0cade678814f0cecb13da435698feae52557acf4
